import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import { languages } from './i18n/settings';
import { PropsWithChildren } from 'react';
import { ThemeProvider } from './providers/themeProvider';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export async function generateStaticParams() {
  return languages.map(lng => ({ lng }));
}

type RootLayoutProps = {
  params: {
    lang: string;
  };
};

export default function RootLayout({ children, params }: PropsWithChildren<RootLayoutProps>) {
  const { lang } = params;

  return (
    <html lang={lang}>
      <ThemeProvider>
        <body className={inter.className}>{children}</body>
      </ThemeProvider>
    </html>
  );
}
